                          
//----------------------------------------------------
// The following code was generated by CUP v0.10g
// Tue Jan 26 09:40:53 GMT 1999
//----------------------------------------------------

package com.antsoft.ant.codecontext;
                 
/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int SWITCH = 91;
  public static final int SLITERAL = 3;
  public static final int EQ = 19;
  public static final int DEFAULT = 62;
  public static final int EXTENDS = 66;
  public static final int AMOD = 37;
  public static final int WHILE = 100;
  public static final int INT = 76;
//static final int STATIC = 88;
  public static final int ASR = 42;
//static final int PRIVATE = 83;
  public static final int FOR = 71;
  public static final int TRY = 97;
  public static final int ASL = 41;
  public static final int IMPLEMENTS = 73;
  public static final int CASE = 57;
  public static final int CHAR = 59;
  public static final int CLITERAL = 6;
  public static final int BOOLEAN = 54;
  public static final int DP = 25;
  public static final int DO = 63;
  public static final int DM = 26;
//static final int FINAL = 68;
  public static final int USR = 32;
//static final int TRANSIENT = 95;
//static final int NATIVE = 79;
  public static final int THROWS = 94;
  public static final int AUSR = 43;
  public static final int TRUE = 96;
//static final int ABSTRACT = 53;
  public static final int IF = 72;
  public static final int ID = 2;
//static final int VOLATILE = 99;
  public static final int RETURN = 86;
  public static final int PACKAGE = 82;
  public static final int NE = 22;
  public static final int SUB = 8;
//static final int PROTECTED = 84;
  public static final int SR = 31;
  public static final int SEMIC = 50;
  public static final int SL = 30;
  public static final int ASUB = 34;
  public static final int BREAK = 55;
  public static final int INTERFACE = 77;
  public static final int ERROR = 1;
  public static final int SUPER = 89;
  public static final int CATCH = 58;
  public static final int FINALLY = 69;
  public static final int INSTANCEOF = 75;
  public static final int DOT = 52;
  public static final int FALSE = 67;
  public static final int GT = 13;
  public static final int RS = 49;
  public static final int BWO = 28;
  public static final int RP = 45;
  public static final int BWN = 16;
  public static final int COMMA = 51;
  public static final int THROW = 93;
  public static final int BYTE = 56;
  public static final int VOID = 98;
  public static final int DIV = 10;
  public static final int SHORT = 87;
  public static final int GE = 21;
  public static final int ABWO = 39;
  public static final int ABWN = 40;
  public static final int BWA = 27;
  public static final int RB = 47;
//static final int PUBLIC = 85;
  public static final int LT = 14;
  public static final int LS = 48;
  public static final int CONTINUE = 61;
  public static final int ASSIGN = 12;
  public static final int ADIV = 36;
  public static final int LP = 44;
  public static final int LO = 24;
  public static final int LN = 15;
  public static final int DOUBLE = 64;
  public static final int ABWA = 38;
  public static final int LE = 20;
//static final int SYNCHRONIZED = 90;
  public static final int NULL = 81;
  public static final int LB = 46;
  public static final int LA = 23;
  public static final int BWEO = 29;
  public static final int QM = 17;
  public static final int MUL = 9;
  public static final int ILITERAL = 4;
  public static final int THIS = 92;
  public static final int FLOAT = 70;
  public static final int AMUL = 35;
  public static final int ADD = 7;
  public static final int EOF = 0;
  public static final int RLITERAL = 5;
  public static final int IMPORT = 74;
  public static final int ELSE = 65;
  public static final int NEW = 80;
  public static final int CLASS = 60;
  public static final int AADD = 33;
  public static final int COLON = 18;
  public static final int LONG = 78;
  public static final int MOD = 11;
  public static final int COMMENT = 101;
  public static final int EOL = 200;
  public static final int MODIFIER = 201;
  public static final int MODIFIER2 = 202;
}

